name: "Label merge conflicts"

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "merge conflicted"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
