name: "Label merge conflicts"

on:
  pull_request_target:
    types: [opened, reopened, synchronize, closed]

jobs:
  triage:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Label merge conflicts
        uses: mschilde/auto-label-merge-conflicts@master
#        run: echo "Hello $LABEL_MERGE_CONFLICT_TOKEN"
#        env:
#          LABEL_MERGE_CONFLICT_TOKEN: ${{ secrets.LABEL_MERGE_CONFLICT_TOKEN }}
        with:
          CONFLICT_LABEL_NAME: "merge conflicted"
#          GITHUB_TOKEN: "$LABEL_MERGE_CONFLICT_TOKEN"
          GITHUB_TOKEN: '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'
