name: "Label merge conflicts"

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Label merge conflicts
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "merge conflicted"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
